apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: v1.35.0                              # 指定 Kubernetes 版本，按需修改
networking:
  podSubnet: 10.244.0.0/16                               # 对应 --pod-network-cidr

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd                                      # 必须与容器运行时一致，通常为 systemd
# 可以在此添加其他 kubelet 配置，如 maxPods、evictionHard 等
evictionHard:
  memory.available: "100Mi"
  nodefs.available: "2%"
  nodefs.inodesFree: "5%"
  imagefs.available: "2%"
  #nodefs.available: 0%
  #imagefs.available: 0%

cpuManagerPolicy: static
cpuManagerPolicyOptions:
  full-pcpus-only: "true"
  strict-cpu-reservation: "true"
topologyManagerPolicy: single-numa-node
topologyManagerScope: pod
memoryManagerPolicy: Static
reservedSystemCPUs: "12,36,13,37"

#NUMA0 CPUs: 0-11,24-35
#GPU0/GPU1: NUMA0
#NUMA1 CPUs: 12-23,36-47
#GPU2/GPU3: NUMA1


kubeReserved:
  memory: "2Gi"

systemReserved:
  memory: "2Gi"

reservedMemory:
- numaNode: 1
  limits:
    memory: "4196Mi"
