apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server
  labels:
    app: iperf3-server
spec:
  runtimeClassName: runc
  containers:
  - name: iperf3
    image: networkstatic/iperf3
    command: ["iperf3"]
    args:
    - "-s"
    ports:
    - containerPort: 5201
    resources:
      requests:
        cpu: "8"
        memory: "32Gi"
      limits:
        cpu: "8"
        memory: "32Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-server
spec:
  selector:
    app: iperf3-server
  ports:
  - name: iperf3
    port: 5201
    targetPort: 5201
