driver:
  enabled: false

toolkit:
  enabled: false

cdi:
  enabled: false

devicePlugin:
  enabled: true
  compatWithCPUManager: true

  config:
    create: true
    name: device-plugin-config
    default: default
    data:
      default: |-
        version: v1
        flags:
          migStrategy: none
          failOnInitError: false
          deviceListStrategy: envvar
          deviceIDStrategy: uuid
          passDeviceSpecs: true

        
