apiVersion: batch/v1
kind: Job
metadata:
  name: runtime-sysbench-memory
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    spec:
      runtimeClassName: kata-qemu-nvidia-gpu
      restartPolicy: Never

        resources:
          requests:
            cpu: "16"
            memory: "64Gi"
          limits:
            cpu: "16"
            memory: "64Gi"
